
spring:
  datasource:
    url: jdbc:mysql://120.79.234.177:3306/db_wx?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: Xfkjcxjd123@
    hikari:
      maximum-pool-size: 20
      max-lifetime: 10
  mvc:
    view:
      suffix: .html
      prefix: /pages/
  resources:
    static-locations: classpath:/static
server:
  port: 80


